# 所有节点均从公开互联网上抓取，使用clash自动检查可用性即可
# 抓取程序已开源： https://github.com/zu1k/proxypool

# port of HTTP
port: 7890

# port of SOCKS5
socks-port: 7891

# (HTTP and SOCKS5 in one port)
# mixed-port: 7890

# redir port for Linux and macOS
# redir-port: 7892

allow-lan: false
mode: rule
log-level: info
external-controller: 127.0.0.1:9090

proxies:
# Shadowsocks 配置范本
# 第一种配置
- name: "搬瓦工SS节点"               # 软件显示的节点名字
  type: ss                                  # 代理类型
  server: 93.179.113.234                         # 服务器 IP
  port: 29333                                 #  端口号
  cipher: chacha20-ietf-poly1305   # 加密方法
  password: "8Ncmpb4zstSeo4iYHq5rfA=="                # SS 密码
  udp: true                                #默认不开启
  

proxy-groups:
  - name: 全局选择
    type: select
    proxies:
      - 搬瓦工SS节点


rules:
  - PROCESS-NAME,Telegram.exe,全局选择
  - DOMAIN-SUFFIX,google.com,全局选择
  - DOMAIN-SUFFIX,github.com,全局选择
  - MATCH,全局选择