port: 7890
socks-port: 7891
mixed-port: 7893
allow-lan: false
mode: rule
log-level: info
external-controller: 127.0.0.1:9090
proxies:
- name: "搬瓦工SS节点"
  type: ss                                  # 代理类型
  server: 93.179.113.234                         # 服务器 IP
  port: 29333                                 #  端口号
  cipher: chacha20-ietf-poly1305   # 加密方法11111
  password: "8Ncmpb4zstSeo4iYHq5rfA=="                # SS 密码
  udp: true                                #默认不开启
proxy-groups:
  - name: 全局选择
    type: select
    proxies:
      - 搬瓦工SS节点
rules: 
  - PROCESS-NAME,com.google.android.gms,全局选择
  - PROCESS-NAME,com.google.android.gsf,全局选择
  - PROCESS-NAME,com.android.vending,全局选择
  - PROCESS-NAME,Battle.net.exe,全局选择
  - PROCESS-NAME,DiabloImmortal.exe,全局选择
  - PROCESS-NAME,Agent.exe,全局选择
  - PROCESS-NAME,chrome.exe,全局选择

  - MATCH,DIRECT
dns:
  enable: true
  enhanced-mode: fake-ip
  nameserver:
    - 114.114.114.114
    - 223.5.5.5
    - 8.8.8.8
  fallback: []
  fake-ip-filter: 
    - dns.msftncsi.com
    - www.msftncsi.com
    - www.msftconnecttest.com
tun:
  enable: true
  stack: gvisor 
  auto-detect-interface: true 
  auto-route: true 
  dns-hijack:
    - 198.18.0.2:53 
